services:
  backend:
    image: 'frappe/erpnext:${FRAPPE_TAG:-v15.88.0}'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - '${V_SITES}:/home/frappe/frappe-bench/sites'
      - '${V_LOGS}:/home/frappe/frappe-bench/logs'
    environment:
      DB_HOST: db
      DB_PORT: '3306'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MARIADB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      FRAPPE_REDIS_CACHE: 'redis://redis-cache:6379'
      FRAPPE_REDIS_QUEUE: 'redis://redis-queue:6379'
  configurator:
    image: 'frappe/erpnext:${FRAPPE_TAG:-v15.88.0}'
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - '-c'
    command: "ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache \"redis://$$REDIS_CACHE\"; bench set-config -g redis_queue \"redis://$$REDIS_QUEUE\"; bench set-config -g redis_socketio \"redis://$$REDIS_QUEUE\"; bench set-config -gp socketio_port $$SOCKETIO_PORT;\n"
    environment:
      DB_HOST: db
      DB_PORT: '3306'
      REDIS_CACHE: 'redis-cache:6379'
      REDIS_QUEUE: 'redis-queue:6379'
      SOCKETIO_PORT: '9000'
    volumes:
      - '${V_SITES}:/home/frappe/frappe-bench/sites'
      - '${V_LOGS}:/home/frappe/frappe-bench/logs'
  create-site:
    image: 'frappe/erpnext:${FRAPPE_TAG:-v15.88.0}'
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - configurator
      - db
      - redis-cache
      - redis-queue
    entrypoint:
      - bash
      - '-c'
    command: "# Espera DB e Redis via /dev/tcp\nuntil (echo > /dev/tcp/db/3306) >/dev/null 2>&1; do echo \"waiting db:3306\"; sleep 2; done;\nuntil (echo > /dev/tcp/redis-cache/6379) >/dev/null 2>&1; do echo \"waiting redis-cache:6379\"; sleep 2; done;\nuntil (echo > /dev/tcp/redis-queue/6379) >/dev/null 2>&1; do echo \"waiting redis-queue:6379\"; sleep 2; done;\n\n# Espera o common_site_config.json do configurator\nexport start=$(date +%s);\nuntil [[ -n $(grep -hs ^ sites/common_site_config.json | jq -r \".db_host // empty\") ]] &&\n      [[ -n $(grep -hs ^ sites/common_site_config.json | jq -r \".redis_cache // empty\") ]] &&\n      [[ -n $(grep -hs ^ sites/common_site_config.json | jq -r \".redis_queue // empty\") ]];\ndo\n  echo \"Waiting for sites/common_site_config.json to be created\";\n  sleep 5;\n  if (( $(date +%s)-start > 180 )); then\n    echo \"could not find sites/common_site_config.json with required keys\";\n    echo \"DEBUG: file contents (if any):\"; grep -hs ^ sites/common_site_config.json || true;\n    exit 1;\n  fi\ndone;\n\necho \"sites/common_site_config.json found\";\nbench new-site \\\n  --mariadb-user-host-login-scope='%' \\\n  --admin-password=$ADMIN_PASSWORD \\\n  --db-root-username=root \\\n  --db-root-password=$DB_ROOT_PASSWORD \\\n  --install-app erpnext \\\n  --set-default ${PRIMARY_SITE:-${COOLIFY_FQDN}};\n"
    environment:
      PRIMARY_SITE: '${PRIMARY_SITE}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      DB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    volumes:
      - '${V_SITES}:/home/frappe/frappe-bench/sites'
      - '${V_LOGS}:/home/frappe/frappe-bench/logs'
  db:
    image: 'mariadb:${MARIADB_TAG:-10.6}'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--skip-character-set-client-handshake'
      - '--skip-innodb-read-only-compressed'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MARIADB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
        - '--password=${DB_ROOT_PASSWORD}'
      interval: 3s
      retries: 20
    volumes:
      - '${V_DB}:/var/lib/mysql'
  frontend:
    image: 'frappe/erpnext:${FRAPPE_TAG:-v15.88.0}'
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: 'backend:8000'
      SOCKETIO: 'websocket:9000'
      FRAPPE_SITE_NAME_HEADER: '${PRIMARY_SITE:-${COOLIFY_FQDN}}'
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: 'off'
      UPSTREAM_REAL_IP_ADDRESS: 172.16.0.0/12
      PROXY_READ_TIMEOUT: '120'
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - '${V_SITES}:/home/frappe/frappe-bench/sites'
      - '${V_LOGS}:/home/frappe/frappe-bench/logs'
  queue-long:
    image: 'frappe/erpnext:${FRAPPE_TAG:-v15.88.0}'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - '--queue'
      - 'long,default,short'
    environment:
      FRAPPE_REDIS_CACHE: 'redis://redis-cache:6379'
      FRAPPE_REDIS_QUEUE: 'redis://redis-queue:6379'
    volumes:
      - '${V_SITES}:/home/frappe/frappe-bench/sites'
      - '${V_LOGS}:/home/frappe/frappe-bench/logs'
  queue-short:
    image: 'frappe/erpnext:${FRAPPE_TAG:-v15.88.0}'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - '--queue'
      - 'short,default'
    environment:
      FRAPPE_REDIS_CACHE: 'redis://redis-cache:6379'
      FRAPPE_REDIS_QUEUE: 'redis://redis-queue:6379'
    volumes:
      - '${V_SITES}:/home/frappe/frappe-bench/sites'
      - '${V_LOGS}:/home/frappe/frappe-bench/logs'
  redis-queue:
    image: 'redis:${REDIS_TAG:-6.2-alpine}'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - '${V_REDISQ}:/data'
  redis-cache:
    image: 'redis:${REDIS_TAG:-6.2-alpine}'
    deploy:
      restart_policy:
        condition: on-failure
  scheduler:
    image: 'frappe/erpnext:${FRAPPE_TAG:-v15.88.0}'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - '${V_SITES}:/home/frappe/frappe-bench/sites'
      - '${V_LOGS}:/home/frappe/frappe-bench/logs'
  websocket:
    image: 'frappe/erpnext:${FRAPPE_TAG:-v15.88.0}'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    environment:
      FRAPPE_REDIS_CACHE: 'redis://redis-cache:6379'
      FRAPPE_REDIS_QUEUE: 'redis://redis-queue:6379'
    volumes:
      - '${V_SITES}:/home/frappe/frappe-bench/sites'
      - '${V_LOGS}:/home/frappe/frappe-bench/logs'
